module.exports=(req,res,next)=>{
    try{
        if(req.session&&req.session.user=='admin'){
            next()
        }
        else{
            res.redirect('/');
        }
    }
    catch(err){
        console.log(err);
    }
}